.unit_test: &howto_unit_test
  stage: test
  before_script:
  - composer install -n --dev
  script:
  -  bin/atoum -f test.php
  cache:
    key: "$CI_BUILD_STAGE"
    paths:
    - bin
    - vendor

unittest_with_php_5.5:
  <<: *howto_unit_test
  image: blitznote/ci-php:5.5

unittest_with_php_5.6:
  <<: *howto_unit_test
  image: blitznote/ci-php:5.6

unittest_with_php_7.0:
  <<: *howto_unit_test
  image: blitznote/ci-php:7.0

unittest_with_php_7.1:
  <<: *howto_unit_test
  image: blitznote/ci-php:7.1
  allow_failure: true
